---
title: "GGM_graph_analysis"
output: html_notebook
---


```{r}
# Tutorial for qgraph: http://psychosystems.org/network-model-selection-using-qgraph-1-3-10/
library("qgraph")
```

## Load Data

```{r}
data = read.csv("../../Data/Complete_01-31-2017/taskdata_imputed.csv", row.names=1,check.names=FALSE)
data$columbia_card_task_hot.information_use = as.integer(data$columbia_card_task_hot.information_use)
```

## Use lavaans lavCor function to automatically detect ordinal data and calculate a perason/polychoric/polyserial orrelation
```{r}
cors = cor_auto(data)
heatmap(cors)
```

```{r, fig.height=20}
label_lookup = read.csv("../../references/variable_name_lookup.csv", row.names=1)
labels=label_lookup[colnames(data),]$Short.Name
corGraph = qgraph(cors, layout="spring", nodeNames=colnames(cors), labels=labels, graph='glasso', sampleSize = nrow(data),legend.cex=.3)
```


```{r, fig.height=14}
centralityPlot(glasso=corGraph,labels=colnames(cors))
```


```{r, fig.height=14}
clusteringPlot(glasso=corGraph,labels=colnames(cors))
```

